# pyright: reportAny=false, reportExplicitAny=false

from typing import Any, Protocol, runtime_checkable


@runtime_checkable
class Logger(Protocol):
    def debug(self, message: str, **context: Any) -> None: ...

    def info(self, message: str, **context: Any) -> None: ...

    def warning(self, message: str, **context: Any) -> None: ...

    def error(self, message: str, **context: Any) -> None: ...

    def critical(self, message: str, **context: Any) -> None: ...

    def exception(self, message: str, **context: Any) -> None: ...
