"""Validation infrastructure for command-line applications.

This module provides the validation system with support for both parameter-scoped
and command-scoped validators. Parameter validators validate individual parameter
values, while command validators validate relationships between multiple parameters.
"""

from ._exceptions import ValidationError
from ._registry import (
    ValidatorFunction,
    ValidatorMetadataType,
    ValidatorRegistry,
    ValidatorRegistryKey,
)
from ._shared import validate_predicate
from .command import default_command_validators
from .parameter import (
    AfterDate,
    AfterDatetime,
    AllMatch,
    Alpha,
    Alphanumeric,
    AnyMatch,
    BeforeDate,
    BeforeDatetime,
    Contains,
    DateRange,
    DatetimeRange,
    EndsWith,
    ForbiddenKeys,
    HasExtensions,
    IsDirectory,
    IsExecutable,
    IsFile,
    IsInteger,
    IsNegative,
    IsNonNegative,
    IsNonPositive,
    IsPositive,
    IsReadable,
    IsWritable,
    ItemType,
    KeyPattern,
    Lowercase,
    MaxKeys,
    MaxTimedelta,
    MinKeys,
    MinTimedelta,
    NoneMatch,
    NotBlank,
    Numeric,
    PathExists,
    Pattern,
    Precision,
    Printable,
    RequiredKeys,
    SequenceContains,
    StartsWith,
    StringValidations,
    TimedeltaRange,
    UniqueItems,
    Uppercase,
    ValuePattern,
    ValueType,
    default_parameter_validators,
)

__all__ = [
    "AfterDate",
    "AfterDatetime",
    "AllMatch",
    "Alpha",
    "Alphanumeric",
    "AnyMatch",
    "BeforeDate",
    "BeforeDatetime",
    "Contains",
    "DateRange",
    "DatetimeRange",
    "EndsWith",
    "ForbiddenKeys",
    "HasExtensions",
    "IsDirectory",
    "IsExecutable",
    "IsFile",
    "IsInteger",
    "IsNegative",
    "IsNonNegative",
    "IsNonPositive",
    "IsPositive",
    "IsReadable",
    "IsWritable",
    "ItemType",
    "KeyPattern",
    "Lowercase",
    "MaxKeys",
    "MaxTimedelta",
    "MinKeys",
    "MinTimedelta",
    "NoneMatch",
    "NotBlank",
    "Numeric",
    "PathExists",
    "Pattern",
    "Precision",
    "Printable",
    "RequiredKeys",
    "SequenceContains",
    "StartsWith",
    "StringValidations",
    "TimedeltaRange",
    "UniqueItems",
    "Uppercase",
    "ValidationError",
    "ValidatorFunction",
    "ValidatorMetadataType",
    "ValidatorRegistry",
    "ValidatorRegistryKey",
    "ValuePattern",
    "ValueType",
    "default_command_validators",
    "default_parameter_validators",
    "validate_predicate",
]
